import { Typography } from "@mui/material";
import styles from "./page.module.css";
import Link from "next/link";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function Copyright() {
  return (
    <Typography variant="body2" color="text.secondary" align="center">
      {"Copyright © "}
      {/* <Link color="inherit" href="#"> */}
      Pablo Ortiz {/* </Link>{" "} */}
      {new Date().getFullYear()}
      {"."}
    </Typography>
  );
}
// className={styles.estilos}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.mar} style={{ marginBottom: 4 }}>
        {children}
        <Copyright />
      </body>
    </html>
  );
}
